### ISSUE TITLE
Doesn't do anything (MacOS)

### ISSUE THREAD

**Issue by DDQW** [mawelborn/ZipContents#4]
Hi,

i installed it via package manager and tried opening a zip. I just get a bunch of hex data but no option to browse anything.

i am running MacOS 12.1 and Sublime Text 4126

do I need to install dependencies or anything via brew? I habe no idea what the problem is

**Comment by mawelborn** [comment]
You shouldn't need to install any dependencies. Everything it needs is included in Sublime Text.

I tried it myself with some zip files I know worked previously and found that it isn't working for me either. I'll have to do a little digging to find out why.

**Comment by mawelborn** [comment]
I found an issue where nothing would be shown after a cold start of Sublime Text. It turns out that reloading the plugin, say by actively working on it, makes it work again. So I never noticed it while developing. Thanks for bringing it to my attention!

I've released a new version that fixes this issue so that ZIP contents are shown after a cold start. Package Control should pick it up soon.
